### PR TITLE
Split notebook and improve docs in them

### PR DESCRIPTION
**Pull request by Samuwhale**
I have started work on splitting the notebooks and adding more information to them (for issue #37). Please let me know your thoughts! It's still WIP, but some feedback doesn't hurt.

### CODE REVIEW

**Review by qubixes — CHANGES_REQUESTED** [review]
Thanks for rearranging the tutorial! I think for now, the outlier notebook can stay as it is. We can improve that in a separate PR. 

As for the usage notebook, I think we can shorten it quite a bit, especially since the users are already supposed to be familiar with the main procedure of metasyn. 

- We can use demo_dataframe instead of demo_file
- I think printing the metaframe clogs up the notebook too much. 
- I don't think the dist_providers need to be given anymore, since all plugins are loaded by default. Could be a point for more detailed documentation.
- The comparisons between disclosure/non-disclosure are probably more easy to read (and shorter) if you use one line for input/output, i.e. Range for fitted/source: ({min}, {max}). Even better if the are lined up and it will be more easy to compare.
- I think it is a nice idea to show that columns can be manually improved, but again I would shorten it in, since it's not really something specific to the disclosure control plugin. 
- Tiny detail: I would use a larger partition_size just to be on the safe side.
- It would be nice to show the effect on the output of a larger partition_size and have a small explanation.

**Review by qubixes — CHANGES_REQUESTED** [review]
Thanks for the update! I have a few points for now:

- The all NA's in the string columns I would consider to be a bug. See my PR in the main metasyn repository. You can test it with the metasyn branch and then remove that section in my opinion.
- Perhaps you can put some distance between the comparison and the `fit_dataframe` output (mainly the progress bar)? You could remove the warning by setting the column to unique and removing the progress bar. I think that would be more suitable, especially since it takes 4s max now.
- There are some unused imports and extra spaces that can be removed.
- The plot is not working for me, since it requires `plt`, which seems to have been removed by accident.

**Comment by Samuwhale** [comment]
Should all be set now!

**Review by qubixes — CHANGES_REQUESTED** [review]
Very nice improvements, still have one or two comments:

- In the last plot, you can synthesize with more than the input number of rows. Then it will remove some of the variance in the plot and will more clearly show the difference between the two.
- There is still the "Manually specifying distributions" paragraph. It could be okay if this is still there, however, it currently says that the disclosure plugin doesn't support all variable types, which I think it actually does. So either we remove the paragraph, or it should be rewritten in a way that is correct after the "bug" in metasyn itself is fixed.

**Comment by qubixes** [comment]
Oh, and feel free to fix the ruff check problem. Otherwise it can also be done in a separate PR.

**Pull request merged**
